# Generated by Django 5.0.2 on 2024-03-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('Date', models.DateField()),
                ('Completed', models.BooleanField(default=False)),
            ],
        ),
    ]
